# coding: utf-8
from django.conf.urls import patterns, include, url

urlpatterns = patterns('reviews.views',
    url(r'^new/$', 'new', name='new'),
    url(r'^add_author/$', 'add_author_to_review', name='add_author_to_review'),
    url(r'^remove_author/$', 'remove_author_from_review', name='remove_author_from_review'),
    url(r'^save_description/$', 'save_description', name='save_description'),
    url(r'^planning/save_source/$', 'save_source', name='save_source'),
    url(r'^planning/remove_source/$', 'remove_source_from_review', name='remove_source_from_review'),
    url(r'^planning/suggested_sources/$', 'suggested_sources', name='suggested_sources'),
    url(r'^planning/add_suggested_sources/$', 'add_suggested_sources', name='add_suggested_sources'),
    url(r'^planning/save_question/$', 'save_question', name='save_question'),
    url(r'^planning/add_question/$', 'add_question', name='add_question'),
    url(r'^planning/remove_question/$', 'remove_question', name='remove_question'),
    url(r'^planning/save_objective/$', 'save_objective', name='save_objective'),
    url(r'^planning/add_criteria/$', 'add_criteria', name='add_criteria'),
    url(r'^planning/remove_criteria/$', 'remove_criteria', name='remove_criteria'),
    url(r'^planning/add_synonym/$', 'add_synonym', name='add_synonym'),
    url(r'^planning/add_new_keyword/$', 'add_new_keyword', name='add_new_keyword'),
    url(r'^planning/save_keyword/$', 'save_keyword', name='save_keyword'),
    url(r'^planning/save_synonym/$', 'save_synonym', name='save_synonym'),
    url(r'^planning/import_pico_keywords/$', 'import_pico_keywords', name='import_pico_keywords'),
    url(r'^planning/remove_keyword/$', 'remove_keyword', name='remove_keyword'),
    url(r'^conducting/generate_search_string/$', 'generate_search_string', name='generate_search_string'),
    url(r'^conducting/save_generic_search_string/$', 'save_generic_search_string', name='save_generic_search_string'),
    url(r'^conducting/import_bibtex/$', 'import_bibtex', name='import_bibtex'),
    url(r'^conducting/source_articles/$', 'source_articles', name='source_articles'),
    url(r'^conducting/article_details/$', 'article_details', name='article_details'),
    url(r'^conducting/save_article_details/$', 'save_article_details', name='save_article_details'),
)