# Generated by Django 3.2.6 on 2021-09-06 23:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0035_auto_20210829_0005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'review', 'verbose_name_plural': 'reviews'},
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='review',
            name='co_authors',
            field=models.ManyToManyField(related_name='co_authors', to=settings.AUTH_USER_MODEL, verbose_name='co-authors'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comparison',
            field=models.CharField(blank=True, max_length=200, verbose_name='comparison'),
        ),
        migrations.AlterField(
            model_name='review',
            name='context',
            field=models.CharField(blank=True, max_length=200, verbose_name='context'),
        ),
        migrations.AlterField(
            model_name='review',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='review',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='intervention',
            field=models.CharField(blank=True, max_length=200, verbose_name='intervention'),
        ),
        migrations.AlterField(
            model_name='review',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='last update'),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.SlugField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='review',
            name='objective',
            field=models.TextField(blank=True, max_length=1000, verbose_name='objective'),
        ),
        migrations.AlterField(
            model_name='review',
            name='outcome',
            field=models.CharField(blank=True, max_length=200, verbose_name='outcome'),
        ),
        migrations.AlterField(
            model_name='review',
            name='population',
            field=models.CharField(blank=True, max_length=200, verbose_name='population'),
        ),
        migrations.AlterField(
            model_name='review',
            name='quality_assessment_cutoff_score',
            field=models.FloatField(default=0.0, verbose_name='quality assessment cutoff score'),
        ),
        migrations.AlterField(
            model_name='review',
            name='sources',
            field=models.ManyToManyField(to='reviews.Source', verbose_name='sources'),
        ),
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('U', 'Unpublished'), ('P', 'Published')], default='U', max_length=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
    ]
