# Generated by Django 3.2.7 on 2021-09-10 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0036_auto_20210906_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='year',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
    ]
