# Generated by Django 3.2.7 on 2021-09-18 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import parsifal.apps.reviews.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('library', '0018_auto_20210829_0005'),
        ('reviews', '0037_auto_20210910_0311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'article', 'verbose_name_plural': 'articles'},
        ),
        migrations.AlterModelOptions(
            name='dataextraction',
            options={'verbose_name': 'data extraction', 'verbose_name_plural': 'data extractions'},
        ),
        migrations.AlterModelOptions(
            name='dataextractionfield',
            options={'ordering': ('order',), 'verbose_name': 'data extraction field', 'verbose_name_plural': 'data extraction fields'},
        ),
        migrations.AlterModelOptions(
            name='dataextractionlookup',
            options={'ordering': ('value',), 'verbose_name': 'lookup value', 'verbose_name_plural': 'lookup values'},
        ),
        migrations.AlterModelOptions(
            name='keyword',
            options={'ordering': ('description',), 'verbose_name': 'keyword', 'verbose_name_plural': 'keywords'},
        ),
        migrations.AlterModelOptions(
            name='qualityanswer',
            options={'ordering': ('-weight',), 'verbose_name': 'quality assessment answer', 'verbose_name_plural': 'quality assessment answers'},
        ),
        migrations.AlterModelOptions(
            name='qualityassessment',
            options={'verbose_name': 'quality assessment', 'verbose_name_plural': 'quality assessment'},
        ),
        migrations.AlterModelOptions(
            name='qualityquestion',
            options={'ordering': ('order',), 'verbose_name': 'quality assessment question', 'verbose_name_plural': 'quality assessment questions'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('order',), 'verbose_name': 'question', 'verbose_name_plural': 'questions'},
        ),
        migrations.AlterModelOptions(
            name='searchresult',
            options={'verbose_name': 'selection result', 'verbose_name_plural': 'selection results'},
        ),
        migrations.AlterModelOptions(
            name='searchsession',
            options={'verbose_name': 'search session', 'verbose_name_plural': 'search sessions'},
        ),
        migrations.AlterModelOptions(
            name='selectioncriteria',
            options={'ordering': ('description',), 'verbose_name': 'selection criteria', 'verbose_name_plural': 'selection criterion'},
        ),
        migrations.AlterModelOptions(
            name='study',
            options={'verbose_name': 'study', 'verbose_name_plural': 'studies'},
        ),
        migrations.AlterModelOptions(
            name='studyselection',
            options={'verbose_name': 'study selection', 'verbose_name_plural': 'study selections'},
        ),
        migrations.AlterField(
            model_name='dataextraction',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.article', verbose_name='article'),
        ),
        migrations.AlterField(
            model_name='dataextraction',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.dataextractionfield', verbose_name='field'),
        ),
        migrations.AlterField(
            model_name='dataextraction',
            name='select_values',
            field=models.ManyToManyField(to='reviews.DataExtractionLookup', verbose_name='select values'),
        ),
        migrations.AlterField(
            model_name='dataextraction',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='dataextraction',
            name='value',
            field=models.TextField(blank=True, null=True, verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='dataextractionfield',
            name='description',
            field=models.CharField(max_length=255, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='dataextractionfield',
            name='field_type',
            field=models.CharField(choices=[('B', 'Boolean Field'), ('S', 'String Field'), ('F', 'Float Field'), ('I', 'Integer Field'), ('D', 'Date Field'), ('O', 'Select One Field'), ('M', 'Select Many Field')], max_length=1, verbose_name='field type'),
        ),
        migrations.AlterField(
            model_name='dataextractionfield',
            name='order',
            field=models.IntegerField(default=0, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='dataextractionfield',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.review', verbose_name='review'),
        ),
        migrations.AlterField(
            model_name='dataextractionlookup',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.dataextractionfield', verbose_name='field'),
        ),
        migrations.AlterField(
            model_name='dataextractionlookup',
            name='value',
            field=models.CharField(max_length=1000, verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='description',
            field=models.CharField(max_length=200, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='related_to',
            field=models.CharField(blank=True, choices=[('P', 'Population'), ('I', 'Intervention'), ('C', 'Comparison'), ('O', 'Outcome')], max_length=1, verbose_name='related to'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='reviews.review', verbose_name='review'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='synonym_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='synonyms', to='reviews.keyword', verbose_name='synonym of'),
        ),
        migrations.AlterField(
            model_name='qualityanswer',
            name='description',
            field=models.CharField(max_length=255, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='qualityanswer',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.review', verbose_name='review'),
        ),
        migrations.AlterField(
            model_name='qualityanswer',
            name='weight',
            field=models.FloatField(verbose_name='weight'),
        ),
        migrations.AlterField(
            model_name='qualityassessment',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews.qualityanswer', verbose_name='answer'),
        ),
        migrations.AlterField(
            model_name='qualityassessment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.article', verbose_name='article'),
        ),
        migrations.AlterField(
            model_name='qualityassessment',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.qualityquestion', verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='qualityassessment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='qualityquestion',
            name='description',
            field=models.CharField(max_length=255, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='qualityquestion',
            name='order',
            field=models.IntegerField(default=0, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='qualityquestion',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.review', verbose_name='review'),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.IntegerField(default=0, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='question',
            name='parent_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='reviews.question', verbose_name='parent question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=500, verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_questions', to='reviews.review', verbose_name='review'),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='documents',
            field=models.ManyToManyField(to='library.Document', verbose_name='documents'),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='imported_file',
            field=models.FileField(null=True, upload_to=parsifal.apps.reviews.models.search_result_file_upload_to, verbose_name='imported file'),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.review', verbose_name='review'),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='search_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews.searchsession', verbose_name='search session'),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.source', verbose_name='source'),
        ),
        migrations.AlterField(
            model_name='searchsession',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.review', verbose_name='review'),
        ),
        migrations.AlterField(
            model_name='searchsession',
            name='search_string',
            field=models.TextField(max_length=10000, verbose_name='search string'),
        ),
        migrations.AlterField(
            model_name='searchsession',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews.source', verbose_name='source'),
        ),
        migrations.AlterField(
            model_name='searchsession',
            name='version',
            field=models.IntegerField(default=1, verbose_name='version'),
        ),
        migrations.AlterField(
            model_name='selectioncriteria',
            name='criteria_type',
            field=models.CharField(choices=[('I', 'Inclusion'), ('E', 'Exclusion')], max_length=1, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='selectioncriteria',
            name='description',
            field=models.CharField(max_length=200, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='selectioncriteria',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.review', verbose_name='review'),
        ),
        migrations.AlterField(
            model_name='source',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='default?'),
        ),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='source',
            name='url',
            field=models.CharField(max_length=200, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='study',
            name='comments',
            field=models.TextField(blank=True, default='', max_length=2000, verbose_name='comments'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='study',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library.document', verbose_name='document'),
        ),
        migrations.AlterField(
            model_name='study',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews.source', verbose_name='source'),
        ),
        migrations.AlterField(
            model_name='study',
            name='status',
            field=models.CharField(choices=[('U', 'Unclassified'), ('R', 'Rejected'), ('A', 'Accepted'), ('D', 'Duplicated')], default='U', max_length=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='study',
            name='study_selection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studies', to='reviews.studyselection', verbose_name='study selection'),
        ),
        migrations.AlterField(
            model_name='study',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='studyselection',
            name='has_finished',
            field=models.BooleanField(default=False, verbose_name='has finished?'),
        ),
        migrations.AlterField(
            model_name='studyselection',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.review', verbose_name='review'),
        ),
        migrations.AlterField(
            model_name='studyselection',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
