# Generated by Django 3.2.7 on 2021-09-18 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0038_auto_20210918_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='abstract',
            field=models.TextField(blank=True, max_length=4000, null=True, verbose_name='abstract'),
        ),
        migrations.AlterField(
            model_name='article',
            name='affiliation',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='affiliation'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author_keywords',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='author keywords'),
        ),
        migrations.AlterField(
            model_name='article',
            name='bibtex_key',
            field=models.CharField(max_length=100, verbose_name='bibtex key'),
        ),
        migrations.AlterField(
            model_name='article',
            name='comments',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='comments'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles_created', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='article',
            name='document_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='document type'),
        ),
        migrations.AlterField(
            model_name='article',
            name='doi',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='doi'),
        ),
        migrations.AlterField(
            model_name='article',
            name='finished_data_extraction',
            field=models.BooleanField(default=False, verbose_name='finished data extraction?'),
        ),
        migrations.AlterField(
            model_name='article',
            name='issn',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='issn'),
        ),
        migrations.AlterField(
            model_name='article',
            name='journal',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='journal'),
        ),
        migrations.AlterField(
            model_name='article',
            name='keywords',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='keywords'),
        ),
        migrations.AlterField(
            model_name='article',
            name='language',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='article',
            name='note',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pages',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='pages'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publisher',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='publisher'),
        ),
        migrations.AlterField(
            model_name='article',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.review', verbose_name='review'),
        ),
        migrations.AlterField(
            model_name='article',
            name='selection_criteria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviews.selectioncriteria', verbose_name='selection criteria'),
        ),
        migrations.AlterField(
            model_name='article',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews.source', verbose_name='source'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('U', 'Unclassified'), ('R', 'Rejected'), ('A', 'Accepted'), ('D', 'Duplicated')], default='U', max_length=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=1000, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='article',
            name='volume',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='volume'),
        ),
        migrations.AlterField(
            model_name='article',
            name='year',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True, verbose_name='year'),
        ),
    ]
