# Generated by Django 3.2.6 on 2021-09-06 01:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0035_auto_20210829_0005'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activities', '0002_alter_activity_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('F', 'Follow'), ('C', 'Comment'), ('S', 'Star')], max_length=1, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='content',
            field=models.CharField(blank=True, max_length=500, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='from user'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews.review', verbose_name='review'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='to_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='to user'),
        ),
    ]
