# Generated by Django 3.2.7 on 2021-09-08 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='invitee_email',
            field=models.EmailField(db_index=True, max_length=254, verbose_name='invitee email'),
        ),
    ]
