# Generated by Django 3.2.6 on 2021-09-04 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0009_auto_20210829_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='dropbox_token',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='mendeley_token',
        ),
        migrations.AlterField(
            model_name='profile',
            name='institution',
            field=models.CharField(blank=True, max_length=50, verbose_name='institution'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=50, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='public_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='public email'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='url',
            field=models.CharField(blank=True, max_length=50, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
